import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir('/Users/boweiouyang/Desktop/femml/cylinder2/output')
i = 8
t_init = 0.0
T = 8.005
TIME_STEP = 0.005
x = np.linspace(t_init, T, int((T - t_init) / TIME_STEP) + 1)
#
# condition = np.loadtxt('./condition/ensemble' + str(i)+ '.txt')
# plt.figure()
# plt.plot(x, condition)
# plt.xlabel('t')
# plt.xlim((t_init, T))
# plt.ylabel(r'$\frac{\Delta t}{\nu h} \|\| \nabla(u^n_j - \langle u \rangle )\|\|^2$')
# plt.savefig('./plot/ensemble' + str(i) + '.png')
# plt.close()
#
# condition = np.loadtxt('./condition/ensemble_penalty' + str(i)+ '.txt')
# plt.figure()
# plt.plot(x, condition)
# plt.xlabel('t')
# plt.xlim((t_init, T))
# plt.ylabel(r'$\frac{\Delta t}{\nu h} \|\| \nabla(u^n_j - \langle u \rangle )\|\|^2$')
# plt.savefig('./plot/ensemble_penalty' + str(i) + '.png')
# plt.close()
#
# condition = np.loadtxt('./condition/ensemble_EVV_type1' + str(i)+ '.txt')
# plt.figure()
# plt.plot(x, condition)
# plt.xlabel('t')
# plt.xlim((t_init, T))
# plt.ylabel(r'$\frac{\Delta t}{\nu h} \|\| \nabla(u^n_j - \langle u \rangle )\|\|^2$')
# plt.savefig('./plot/ensemble_EVV_type1' + str(i) + '.png')
# plt.close()
#
# condition = np.loadtxt('./condition/ensemble_penalty_EVV_evvtype1_evv1type0' + str(i)+ '.txt')
# plt.figure()
# plt.plot(x, condition)
# plt.xlabel('t')
# plt.xlim((t_init, T))
# plt.ylabel(r'$\frac{\Delta t}{\nu h} \|\| \nabla(u^n_j - \langle u \rangle )\|\|^2$')
# plt.savefig('./plot/ensemble_penalty_EVV_evvtype1_evv1type0' + str(i) + '.png')
# plt.close()
#
# condition = np.loadtxt('./condition/ensemble_penalty_EVV_evvtype1_evv1type1' + str(i)+ '.txt')
# plt.figure()
# plt.plot(x, condition)
# plt.xlabel('t')
# plt.xlim((t_init, T))
# plt.ylabel(r'$\frac{\Delta t}{\nu h} \|\| \nabla(u^n_j - \langle u \rangle )\|\|^2$')
# plt.savefig('./plot/ensemble_penalty_EVV_evvtype1_evv1type1' + str(i) + '.png')
# plt.close()
#
# condition = np.loadtxt('./condition/ensemble_penalty_EVV_evvtype2_evv1type0' + str(i)+ '.txt')
# plt.figure()
# plt.plot(x, condition)
# plt.xlabel('t')
# plt.xlim((t_init, T))
# plt.ylabel(r'$\frac{\Delta t}{\nu h} \|\| \nabla(u^n_j - \langle u \rangle )\|\|^2$')
# plt.subplots_adjust(left=0.15)
# plt.savefig('./plot/ensemble_penalty_EVV_evvtype2_evv1type0' + str(i) + '.png')
# plt.close()
#
# condition = np.loadtxt('./condition/ensemble_penalty_EVV_evvtype2_evv1type1' + str(i)+ '.txt')
# plt.figure()
# plt.plot(x, condition)
# plt.xlabel('t')
# plt.xlim((t_init, T))
# plt.ylabel(r'$\frac{\Delta t}{\nu h} \|\| \nabla(u^n_j - \langle u \rangle )\|\|^2$')
# plt.savefig('./plot/ensemble_penalty_EVV_evvtype2_evv1type1' + str(i) + '.png')
# plt.close()

divu = np.loadtxt('./divu_avg/ensemble_EVV_type1' + '.txt')
plt.figure()
plt.plot(x, divu)
plt.xlabel('t')
plt.xlim((t_init, T))
plt.ylabel(r'$\|\|\nabla\cdot u\|\|$')
plt.savefig('./plot/ensemble_EVV_divu_avg_type1' + '.png')
plt.close()

divu = np.loadtxt('./divu_avg/ensemble_EVV_type2' + '.txt')
plt.figure()
plt.plot(x, divu)
plt.xlabel('t')
plt.xlim((t_init, T))
plt.ylabel(r'$\|\|\nabla\cdot u\|\|$')
plt.savefig('./plot/ensemble_EVV_divu_avg_type2' + '.png')
plt.close()

divu = np.loadtxt('./divu_avg/ensemble_penalty_EVV_evvtype1_evv1type1' + '.txt')
plt.figure()
plt.plot(x, divu)
plt.xlabel('t')
plt.xlim((t_init, T))
plt.ylabel(r'$\|\|\nabla\cdot u\|\|$')
plt.savefig('./plot/ensemble_penalty_EVV_divu_evvtype1_evv1type1' + '.png')
plt.close()

divu = np.loadtxt('./divu_avg/ensemble_penalty_EVV_evvtype2_evv1type1' + '.txt')
plt.figure()
plt.plot(x, divu)
plt.xlabel('t')
plt.xlim((t_init, T))
plt.ylabel(r'$\|\|\nabla\cdot u\|\|$')
plt.savefig('./plot/ensemble_penalty_EVV_divu_evvtype2_evv1type1' + '.png')
plt.close()